use_frameworks!
platform :ios, '12.0'

target 'QuickTodo' do
  # core RxSwift
  pod 'RxSwift', '5.1.1'
  pod 'RxCocoa', '5.1.1'
  pod 'RxDataSources', '~> 4.0'

  # Community projects
  pod 'Action', '~> 4.0'
  pod 'NSObject+Rx', '~> 5.1'
  
  # Realm database
  pod 'RealmSwift', '~> 5.0'
  pod 'RxRealm', '~> 3.0'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'
    end
  end
end
